#!/sbin/sh

is_mounted() {
	if [ ! -z "$2" ]; then
		cat /proc/mounts | grep $1 | grep $2, >/dev/null
	else
		cat /proc/mounts | grep $1 >/dev/null
	fi
	return $?
}

setup_add () {
	if grep -q "item.1.${1}=1" "${setup_prop}"; then
		echo "${2}=1" >> "${nanomod_setup}"
	else	echo "${2}=0" >> "${nanomod_setup}"
	fi
}

apps_add () {
	if grep -q "item.1.${1}=1" "${apps_prop}"; then
		echo "${2}" >> "${nanomod_apps}"
	fi
}

if (is_mounted /data); then
	mount -orw,remount /data >/dev/null
else	mount -orw /data >/dev/null
fi

configpath="/data"
nanomod_apps="${configpath}/.nanomod-apps"
nanomod_overlay="${configpath}/.nanomod-overlay"
nanomod_setup="${configpath}/.nanomod-setup"

aromapath="/tmp/aroma-data"
setup_prop="${aromapath}/setup.prop"
store_prop="${aromapath}/store.prop"
apps_prop="${aromapath}/apps.prop"
debloat_prop="${aromapath}/debloat.prop"

for setupfile in ${nanomod_apps} ${nanomod_overlay} ${nanomod_setup}; do
	rm -f "${setupfile}"
done

setup_add 1 nanomod_microg
setup_add 2 nanomod_fdroid
setup_add 3 nanomod_apps
setup_add 4 nanomod_overlay
setup_add 5 nanomod_zelda
setup_add 6 nanomod_mapsv1
setup_add 7 nanomod_init
setup_add 8 nanomod_gsync
setup_add 9 nanomod_swipe
setup_add 10 nanomod_forcesystem

if grep -q "selected.1=1" "${store_prop}"; then
	echo "nanomod_play=0" >> "${nanomod_setup}"
elif grep -q "selected.1=2" "${store_prop}"; then
	echo "nanomod_play=1" >> "${nanomod_setup}"
elif grep -q "selected.1=3" "${store_prop}"; then
	echo "nanomod_play=2" >> "${nanomod_setup}"
fi

apps_add 1 Adaway
apps_add 2 Amaze
apps_add 3 AnysoftKeyboard
apps_add 4 FaceSlim
apps_add 5 HackerKeyboard
apps_add 6 K9Mail
apps_add 7 KeePassDroid
apps_add 8 KernelAdiutor
apps_add 9 Lightning
apps_add 10 MPV
apps_add 11 NewPipe
apps_add 12 Oandbackup
apps_add 13 Odyssey
apps_add 14 OpenCamera
apps_add 15 OpenKeyChain
apps_add 16 OpenLauncher
apps_add 17 OpenWeatherMapProvider
apps_add 18 OpenVPN
apps_add 19 QKSMS
apps_add 20 SimpleCalendar
apps_add 21 SimpleGallery
apps_add 22 Substratum
apps_add 23 Termux
apps_add 24 Twidere
apps_add 25 XDALabs
apps_add 26 YahooWeatherProvider

exit 0
