#!/system/bin/sh

media_rw=$(mount | grep "on /mnt/media_rw" | sed -e 's,.*/mnt,/mnt,g;s, type.*,,g')
storage=$(mount | grep "^${media_rw} on /storage" | sed -e 's,.*/storage,/storage,g;s, type.*,,g')

if [[ -e /external_sd ]]; then
	mount -orw,remount /
	rm -f /external_sd
	mount -oro,remount /
fi

if [[ -d ${storage} ]]; then
	mount -orw,remount /
	ln -sf ${storage} /external_sd
	mount -oro,remount /
fi
