#!/sbin/sh

APPS="BasicDreams
Browser
Calendar
Camera2
CMFileManager
Eleven
Email
Exchange2
FMRadio
Gallery2
Gello
Jelly
messaging
mGerrit
OmniSwitch
Phonograph
PhotoTable
Recorder
ResurrectionStats
Screencast
Slimperience
Snap
SnapdragonCamera
SoundRecorder
Stk
ViaBrowser
Wallpaper
WallpaperBackup
WallpaperPickerGoogle"

is_mounted() {
	if [ ! -z "$2" ]; then
		cat /proc/mounts | grep $1 | grep $2, >/dev/null
	else
		cat /proc/mounts | grep $1 >/dev/null
	fi
	return $?
}

debloat_system () {
	if (is_mounted /system); then
		mount -orw,remount /system || error "!! failed to remount system read-write"
	else	mount -orw /system || error "!! failed to mount system read-write"
	fi

	for app in ${APPS}; do
		if [[ -d /system/app/${app} ]; then
			rm -rf /system/app/${app}
			echo "${app} removed from /system/app"
		elif [[ -d /system/priv-app/${app} ]; then
			rm -rf /system/priv-app/${app}
			echo "${app} removed from /system/priv-app"
		else	echo "${app} is not installed"
		fi
	done

	umount /system
}

error () {
	echo "${@}"
	exit 1
}


[[ ! -d /twres ]] && error "Not running from TWRP, exiting"
is_mounted /data || mount /data
[[ -f /data/magisk.img ]] && error "Magisk is installed, exiting"

echo "NanoMod force-debloat script

This script will actually remove apps from

	/system/app
	/system/priv-app

Are you sure you want to proceed?

Enter [y] / [j]
"

read -r USER_INPUT

case ${USER_INPUT} in
	y | Y | j | J )
		debloat_system
	;;

	"" )
		error "No user input, exiting"
	;;

	* )
		error "Unknown user input, exiting"
	;;
esac
