#!/system/bin/sh

# wait until boot completed
until [ `getprop sys.boot_completed`. = 1. ]; do sleep 1; done

LOGDIR="${MODDIR}"/logcats

echo "logcat init script"
echo "Starting Automatic Cleaning at $(date +"%m-%d-%Y %H:%M:%S")"

[[ ! -d ${LOGDIR} ]] && mkdir -p ${LOGDIR}

# remove files older than a week to prevent pollution
find /data/adb/logcat/ -print -mtime +8 -exec rm -f {} \; 2>/dev/null

echo "Automatic Cleaning finished at $(date +"%m-%d-%Y %H:%M:%S")"
echo "Recording logcat to: ${LOGDIR}/${CURDATE}"

logcat -f "${LOGDIR}/${CURDATE}" &
