#!/system/bin/sh

echo "logscleaner init script"
echo "Starting Automatic Cleaning $(date +"%m-%d-%Y %H:%M:%S")"

# remove files older than a week to prevent pollution

# filemask: *
for logpath in /data/log /data/slog /data/tombstones \
	/data/system/usagestats/0; do
	find ${logpath} -mtime +8 -type f -exec rm -f {} \;
done

# filemask: *.tmp
for logpath in /data/data/*/*/* /data/data/*/*/*/* \
	/data/backup/pending/; do
	find ${logpath} -mtime +8 -type f -name '*.tmp' -exec rm -f {} \;
done

# filemask: *.apk
for logpath in /data/local/ /data/local/tmp; do
	find ${logpath} -mtime +8 -type f -name '*.apk' -exec rm -f {} \;
done

# filemask: *.*
for logpath in /cache /cache/recovery /data/system/dropbox; do
	find ${logpath} -mtime +8 -type f -name '*.*' -exec rm -f {} \;
done

echo "Automatic Cleaning finished at $(date +"%m-%d-%Y %H:%M:%S")"
